USE music;

ALTER TABLE Album
ADD CONSTRAINT fk_artist FOREIGN KEY (ArtistID) 
REFERENCES Artist(ArtistID) 
ON DELETE CASCADE;

ALTER TABLE Songs
ADD CONSTRAINT fk_album FOREIGN KEY (AlbumID) 
REFERENCES Album(AlbumID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE Songs
ADD CONSTRAINT fk_genre FOREIGN KEY (GenreID) 
REFERENCES Genres(GenreID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE Playlists
ADD CONSTRAINT fk_user FOREIGN KEY (UserID) 
REFERENCES Users(UserID) 
ON DELETE CASCADE;

ALTER TABLE Playlist_Songs
ADD CONSTRAINT fk_playlist FOREIGN KEY (PlaylistID) 
REFERENCES Playlists(PlaylistID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE Playlist_Songs
ADD CONSTRAINT fk_song FOREIGN KEY (SongID) 
REFERENCES Songs(SongID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE Playlist_Songs
ADD CONSTRAINT fk_playlist FOREIGN KEY (PlaylistID) 
REFERENCES Playlists(PlaylistID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE Library_Songs
ADD CONSTRAINT fk_library FOREIGN KEY (LibraryID) 
REFERENCES Library(LibraryID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE Ratings
ADD CONSTRAINT fk_song1 FOREIGN KEY (SongID) 
REFERENCES Songs(SongID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE Ratings
ADD CONSTRAINT fk_user2 FOREIGN KEY (UserID) 
REFERENCES Users(UserID) 
ON DELETE CASCADE;

ALTER TABLE ArtistFollow
ADD CONSTRAINT fk_user3 FOREIGN KEY (UserID) 
REFERENCES Users(UserID) 
ON DELETE CASCADE;

ALTER TABLE ArtistFollow
ADD CONSTRAINT fk_artist2 FOREIGN KEY (ArtistID) 
REFERENCES Artist(ArtistID) 
ON DELETE CASCADE;

ALTER TABLE Library_Songs 
ADD CONSTRAINT fk_library FOREIGN KEY (LibraryID) 
REFERENCES Library(LibraryID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

ALTER TABLE  Library_Songs 
ADD CONSTRAINT fk_song3 FOREIGN KEY (SongID) 
REFERENCES Songs(SongID) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

Alter table Album drop column GenreID;
